name: Build code analytics data
on:
  pull_request:
  schedule:
    - cron: '0 5 * * *'  # once per day at midnight ET
  workflow_dispatch:

jobs:
  build-analytics-data:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required for versioneer to determine the version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Sphinx dependencies and package
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[docs]"
          sudo apt install cloc

      - name: build the docs
        run: |
          rm -f data/cloc_stats.yaml
          rm -f data/commit_stats.yaml
          rm -f data/git_paths.yaml
          rm -f data/release_timelines.yaml
          rm -f data/contributors.tsv
          cd docs
          make allclean
          make html

      # Commit all changed files back to the repository
      - name: Push changes back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          file_pattern: 'data/*.yaml data/*.tsv'
          commit_message: "Automatic update of the code statistics YAML files"
          commit_user_name: NWB Bot
          commit_user_email: 32185786+nwb-bot@users.noreply.github.com
          commit_author: NWB Bot <32185786+nwb-bot@users.noreply.github.com>
