name: A test workflow
on:
  push:
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Cancel non-latest runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required for versioneer to determine the version

      - name: Run stuff
        run: |
          echo `date` >> test.txt

      # Commit all changed files back to the repository
      - name: Push changes back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'test.txt data/*.yaml'
          commit_message: "Automatic update of the code statistics YAML files"
          commit_user_name: NWB Bot
          commit_user_email: neurodatawithoutborders.appv@gmail.com
          commit_author: NWB Bot <nwb-bot@users.noreply.github.com>
